spring:
    application:
        name: testeconta
    h2:
        console:
            enabled: true
            path: /h2
            
datasource:
    url: jdbc:h2:mem:testeconta
    username: test
    password: 1234

server:
    port: 8080
    context-path: /testecontaapi
